# Generated by Django 4.2.11 on 2024-04-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='button_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Кнопка'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='button_ru',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Кнопка'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='description_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='description_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='title_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='title_ru',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Заголовок'),
        ),
    ]
