# Generated by Django 4.2.11 on 2024-05-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='banners/', verbose_name='Картинка'),
        ),
    ]
