# Generated by Django 4.2.11 on 2024-05-30 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
