# Generated by Django 4.2.11 on 2024-04-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
