# Generated by Django 4.2.11 on 2024-04-05 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_is_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner1', models.ImageField(upload_to='banners/')),
                ('banner2', models.ImageField(upload_to='banners/')),
                ('banner3', models.ImageField(upload_to='banners/')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('descrition', models.TextField(verbose_name='Описание')),
                ('counter1_title', models.CharField(max_length=30)),
                ('counter2_title', models.CharField(max_length=30)),
                ('counter3_title', models.CharField(max_length=30)),
                ('counter1_value', models.CharField(max_length=30)),
                ('counter2_value', models.CharField(max_length=30)),
                ('counter3_value', models.CharField(max_length=30)),
                ('button_link', models.URLField()),
                ('button', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv_image', models.ImageField(upload_to='banners/')),
                ('adv_title', models.CharField(max_length=30)),
                ('adv_description', models.CharField(max_length=100)),
                ('adv_button_link', models.URLField()),
                ('adv_button', models.CharField(max_length=30)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.mainpage')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Рекламы',
            },
        ),
    ]
