# Generated by Django 4.2.11 on 2024-04-01 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='product',
        ),
    ]
