# Generated by Django 4.2.11 on 2024-04-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_image_product'),
    ]

    operations = [

        migrations.AlterField(
            model_name='product',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_meta_images'),
        ),
    ]
