# Generated by Django 4.2.11 on 2024-04-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_mainpage_advertisement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='adv_button',
            new_name='button',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='adv_button_link',
            new_name='button_link',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='adv_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='adv_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='adv_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='mainpage',
            old_name='descrition',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='button',
            field=models.CharField(max_length=50, verbose_name='Кнопка'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='button_link',
            field=models.URLField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='counter1_title',
            field=models.CharField(max_length=30, verbose_name='Значение показателя 1'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='counter1_value',
            field=models.CharField(max_length=30, verbose_name='Название показателя 1'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='counter2_title',
            field=models.CharField(max_length=30, verbose_name='Значение показателя 2'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='counter2_value',
            field=models.CharField(max_length=30, verbose_name='Название показателя 2'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='counter3_title',
            field=models.CharField(max_length=30, verbose_name='Название показателя 3'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='counter3_value',
            field=models.CharField(max_length=30, verbose_name='Значение показателя 3'),
        ),
    ]
