# Generated by Django 4.2.11 on 2024-04-24 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.color'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.size'),
        ),
    ]
