# Generated by Django 4.2.11 on 2024-05-15 06:38

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_image_variant_image_color_image_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='characteristic',
            options={'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='reviewimage',
            options={'verbose_name': 'Картинка отзыва', 'verbose_name_plural': 'Картинки отзывов'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.AlterModelOptions(
            name='sizechart',
            options={'verbose_name': 'Карта размеров', 'verbose_name_plural': 'Карты размеров'},
        ),
        migrations.AlterModelOptions(
            name='sizechartitem',
            options={'verbose_name': 'Элемент карты размеров', 'verbose_name_plural': 'Элементы карты размеров'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name': 'Вариант', 'verbose_name_plural': 'Варианты'},
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='review',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='review',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='size',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='size',
            name='name_ru',
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, help_text='The logo of the brand', null=True, upload_to='brand_logos/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(help_text='The name of the brand', max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='background_color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=25, null=True, samples=None, verbose_name='Фоновый цвет'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Мета описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=59, verbose_name='Мета заголовок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='promotion',
            field=models.BooleanField(default=False, verbose_name='Продвижение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.IntegerField(choices=[(0, 'For men'), (1, 'For woman'), (2, 'For children'), (3, 'Unisex')], default=3, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type_en',
            field=models.IntegerField(choices=[(0, 'For men'), (1, 'For woman'), (2, 'For children'), (3, 'Unisex')], default=3, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type_ru',
            field=models.IntegerField(choices=[(0, 'For men'), (1, 'For woman'), (2, 'For children'), (3, 'Unisex')], default=3, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключь'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='key_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключь'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='key_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключь'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='value_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='value_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Хекс'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новый продукт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='Топ продукт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=models.JSONField(blank=True, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Мета описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_meta_images/', verbose_name='Мета картинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=59, null=True, verbose_name='Мета заголовок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Минимальная цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='catalog.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='size',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=25, null=True, samples=None, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percent', 'Percent'), ('unit', 'Unit')], default=0, help_text='Type of the discount - either a percent or a fixed unit.', max_length=7, null=True, verbose_name='Тмп скидки'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount amount, either in percentage or fixed unit based on the discount type.', max_digits=10, null=True, verbose_name='Значение скидки'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Главный'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.size', verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
    ]
