# Generated by Django 4.2.11 on 2024-04-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='size',
        ),
        migrations.AddField(
            model_name='variant',
            name='size',
            field=models.ManyToManyField(related_name='variants', to='catalog.size'),
        ),
    ]
