# Generated by Django 4.2.11 on 2024-05-17 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0005_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='categories',
            field=models.ManyToManyField(related_name='brands', to='catalog.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='product_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='main_image',
            field=models.BooleanField(default=False, verbose_name='Главная картинка'),
        ),
        migrations.AlterField(
            model_name='image',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Мини изображение'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Позьователь'),
        ),
        migrations.AlterField(
            model_name='sizechart',
            name='categories',
            field=models.ManyToManyField(related_name='size_charts', to='catalog.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='sizechart',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sizechartitem',
            name='size',
            field=models.CharField(max_length=10, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='sizechartitem',
            name='size_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.sizechart', verbose_name='Элемент карты размеров'),
        ),
    ]
