# Generated by Django 4.2.11 on 2024-04-05 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_adv_button_advertisement_button_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='button',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Кнопка'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='button_link',
            field=models.URLField(blank=True, null=True, verbose_name='Сылка'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.mainpage'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='banner1',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='banner2',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='banner3',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='button',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Кнопка'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='button_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='counter1_title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Значение показателя 1'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='counter1_value',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название показателя 1'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='counter2_title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Значение показателя 2'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='counter2_value',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название показателя 2'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='counter3_title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название показателя 3'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='counter3_value',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Значение показателя 3'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
    ]
