# Generated by Django 4.2.11 on 2024-04-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_staticpage_image_alter_product_meta_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
