# Generated by Django 4.2.11 on 2024-04-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_advertisement_page_remove_mainpageslider_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name_en',
            field=models.CharField(help_text='The name of the brand', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_ru',
            field=models.CharField(help_text='The name of the brand', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='type_en',
            field=models.IntegerField(choices=[(0, 'For men'), (1, 'For woman'), (2, 'For children'), (3, 'Unisex')], default=3, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='type_ru',
            field=models.IntegerField(choices=[(0, 'For men'), (1, 'For woman'), (2, 'For children'), (3, 'Unisex')], default=3, null=True),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='key_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Key'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='key_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Key'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='value_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Value'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='value_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Value'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='review',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='size',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_ru',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
