# Generated by Django 4.2.11 on 2024-04-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_mainpage_banner1_link_mainpage_banner2_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Рекламу', 'verbose_name_plural': 'Рекламы'},
        ),
        migrations.AlterModelOptions(
            name='mainpageslider',
            options={'verbose_name': 'Слайдер'},
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='button_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
