# Generated by Django 4.2.11 on 2024-05-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='categories',
            field=models.ManyToManyField(related_name='sizes', to='catalog.category', verbose_name='Категории'),
        ),
    ]
