# Generated by Django 4.2.11 on 2024-04-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_advertisement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageslider',
            name='description',
            field=models.CharField(default=1, max_length=100, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpageslider',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='Загловок'),
            preserve_default=False,
        ),
    ]
