# Generated by Django 4.2.11 on 2024-05-24 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='catalog.color', verbose_name='Цвет'),
            preserve_default=False,
        ),
    ]
