# Generated by Django 4.2.11 on 2024-04-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_mainpageslider_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageslider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slider/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_meta_images/'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static_pages/'),
        ),
    ]
