# Generated by Django 4.2.11 on 2024-05-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_review_rating_alter_review_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='meta_description',
        ),
        migrations.AddField(
            model_name='category',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Мета изображение'),
        ),
    ]
