# Generated by Django 4.2.11 on 2024-07-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20240704_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество'),
        ),
    ]
