# Generated by Django 4.2.11 on 2024-07-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_variant_price_alter_variant_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='discounted_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
