# Generated by Django 4.2.11 on 2024-07-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_variant_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Максимальная цена'),
        ),
    ]
