# Generated by Django 4.2.11 on 2024-04-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_visit',
            field=models.BooleanField(default=True),
        ),
    ]
