# Generated by Django 4.2.11 on 2024-04-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='street',
            field=models.CharField(default=1, max_length=100, verbose_name='Улица'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
    ]
