# Generated by Django 4.2.11 on 2024-05-31 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fcm_token',
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_registration_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='FCM Registration ID'),
        ),
    ]
