# Generated by Django 4.2.11 on 2024-05-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_fcm_token_user_fcm_registration_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fcm_registration_id',
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Токен'),
        ),
    ]
