# Generated by Django 4.2.11 on 2024-06-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_fcm_registration_id_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_notifications',
            field=models.BooleanField(default=True, verbose_name='Получать уведомления'),
        ),
    ]
