# Generated by Django 4.2.11 on 2024-05-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_options_ordering_domain'),
        ('sites', '0004_alter_site_options'),
    ]

    operations = [
    ]
