# Generated by Django 4.2.11 on 2024-04-29 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner1', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('banner1_link', models.URLField(blank=True, null=True)),
                ('banner2', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('banner2_link', models.URLField(blank=True, null=True)),
                ('banner3', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('banner3_link', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('counter1_title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Значение показателя 1')),
                ('counter1_value', models.CharField(blank=True, max_length=30, null=True, verbose_name='Название показателя 1')),
                ('counter2_title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Значение показателя 2')),
                ('counter2_value', models.CharField(blank=True, max_length=30, null=True, verbose_name='Название показателя 2')),
                ('counter3_value', models.CharField(blank=True, max_length=30, null=True, verbose_name='Значение показателя 3')),
                ('counter3_title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Название показателя 3')),
                ('button_link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('button', models.CharField(blank=True, max_length=50, null=True, verbose_name='Кнопка')),
            ],
            options={
                'verbose_name': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static_pages/')),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Static Page',
                'verbose_name_plural': 'Static Pages',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MainPageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Загловок')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider/')),
                ('link', models.URLField(blank=True, null=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.mainpage')),
            ],
            options={
                'verbose_name': 'Слайдер',
            },
        ),
    ]
