# Generated by Django 4.2.11 on 2024-05-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name': 'Главная страница', 'verbose_name_plural': 'Главная страница'},
        ),
        migrations.AlterModelOptions(
            name='mainpageslider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдер'},
        ),
        migrations.AlterModelOptions(
            name='staticpage',
            options={'ordering': ['title'], 'verbose_name': 'Статичные страницы', 'verbose_name_plural': 'Статичные страницы'},
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static_pages/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Мета описание'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Мета описание'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='meta_description_ru',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Мета описание'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='static_pages_meta/', verbose_name='Мета описание'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Мета заголовок'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Мета заголовок'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Мета заголовок'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='title_en',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
    ]
