# Generated by Django 4.2.11 on 2024-04-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='button_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Кнопка'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='button_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Кнопка'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='counter1_title_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Значение показателя 1'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='counter1_title_ru',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Значение показателя 1'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='counter1_value_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название показателя 1'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='counter1_value_ru',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название показателя 1'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='counter2_title_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Значение показателя 2'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='counter2_title_ru',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Значение показателя 2'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='counter2_value_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название показателя 2'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='counter2_value_ru',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название показателя 2'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='counter3_title_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название показателя 3'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='counter3_title_ru',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название показателя 3'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='counter3_value_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Значение показателя 3'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='counter3_value_ru',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Значение показателя 3'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='mainpageslider',
            name='description_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='mainpageslider',
            name='description_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='mainpageslider',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Загловок'),
        ),
        migrations.AddField(
            model_name='mainpageslider',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Загловок'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='meta_description_ru',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='static_pages_meta/'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='title_en',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
