# Generated by Django 4.2.11 on 2024-05-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_mainpage_options_alter_mainpageslider_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='static_pages_meta/', verbose_name='Мета изображение'),
        ),
    ]
