# Generated by Django 4.2.11 on 2024-04-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_mainpage_button_en_mainpage_button_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='counter1_value_en',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='counter1_value_ru',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='counter2_value_en',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='counter2_value_ru',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='counter3_value_en',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='counter3_value_ru',
        ),
    ]
