# Generated by Django 4.2.11 on 2024-05-22 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_staticpage_meta_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
                ('icon', models.FileField(upload_to='social_icons')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.contacts')),
            ],
            options={
                'verbose_name': 'Ссылка соцсети',
                'verbose_name_plural': 'Ссылки соцсетей',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100)),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.contacts')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.contacts')),
            ],
            options={
                'verbose_name': 'Имейл',
                'verbose_name_plural': 'Имейлы',
            },
        ),
    ]
