# Generated by Django 4.2.11 on 2024-05-22 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
                ('icon', models.FileField(upload_to='payment_icons')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.contacts')),
            ],
            options={
                'verbose_name': 'Ссылка оплаты',
                'verbose_name_plural': 'Ссылки оплаты',
            },
        ),
    ]
