# Generated by Django 4.2.11 on 2024-05-29 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_faq_answer_alter_faq_answer_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpageslider',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mainpageslider',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='mainpageslider',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='mainpageslider',
            name='title',
        ),
        migrations.RemoveField(
            model_name='mainpageslider',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='mainpageslider',
            name='title_ru',
        ),
    ]
