# Generated by Django 4.2.11 on 2024-05-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_mainpageslider_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='meta_description',
            field=models.TextField(default=1, verbose_name='Мета Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='meta_image',
            field=models.ImageField(default=1, upload_to='layout/meta_image', verbose_name='Мета Картинки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='meta_title',
            field=models.CharField(default=1, max_length=255, verbose_name='Мета Заголовок'),
            preserve_default=False,
        ),
    ]
