# Generated by Django 4.2.11 on 2024-05-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_contacts_meta_description_contacts_meta_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Мета Описание'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='layout/meta_image', verbose_name='Мета Картинки'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета Заголовок'),
        ),
    ]
