# Generated by Django 4.2.11 on 2024-06-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_contacts_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageslider',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Мини изображение'),
        ),
    ]
