# Generated by Django 4.2.11 on 2024-06-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_mainpageslider_small_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageslider',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to='slider-mobile/', verbose_name='Мини изображение'),
        ),
    ]
