# Generated by Django 4.2.11 on 2024-06-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_remove_contacts_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpagelayoutmeta',
            options={'verbose_name': 'Мета главная страница', 'verbose_name_plural': 'Мета главная страница'},
        ),
    ]
