# Generated by Django 4.2.11 on 2024-06-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_mainpagelayoutmeta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageslider',
            name='link_mobile',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка для мини изображение'),
        ),
        migrations.AlterField(
            model_name='mainpageslider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slider/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='mainpageslider',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
