# Generated by Django 4.2.11 on 2024-06-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_mainpageslider_link_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpageslider',
            name='link_mobile',
        ),
        migrations.AlterField(
            model_name='mainpageslider',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to='slider-mobile/', verbose_name='Изображение для телефона'),
        ),
    ]
