# Generated by Django 4.2.11 on 2024-04-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_order_number_alter_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Не оплачено'), (1, 'Платеж в процессе'), (2, 'Оплачено')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'В процессе'), (1, 'Доставлено'), (3, 'Доставка отменена')], default=0),
        ),
    ]
