# Generated by Django 4.2.11 on 2024-05-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'В процессе'), (1, 'Доставлено'), (2, 'Доставка отменена'), (3, 'Новый'), (4, 'Отправлено')], default=0, verbose_name='Статус заказа'),
        ),
    ]
