# Generated by Django 4.2.11 on 2024-05-31 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_payment_status_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'verbose_name': 'История заказов', 'verbose_name_plural': 'История заказов'},
        ),
    ]
